services:
  wordpress:
    build:
      dockerfile: Dockerfile-fpm
      context: .
      args:
        PHP_VERSION: 8
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_URL: "localhost:8080"
      WORDPRESS_TITLE: "test wordpress title"
      WORDPRESS_ADMIN_USER: test
      WORDPRESS_ADMIN_PASS: test
      WORDPRESS_ADMIN_EMAIL: test@mailinator.com
      WORDPRESS_BACKUP: "0 0,6,12,18 * * *"
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
      - backup:/backup
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    environment:
      - FPM_SERVER=wordpress:9000
    volumes:
      - wordpress:/var/www/html
      - ./opt/nginx/conf:/etc/nginx/conf.d
      - ./opt/nginx/template:/etc/nginx/templates
    ports:
      - '8080:80'
  db:
    image: mariadb:latest
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  backup:
