FROM koalaphils/php:8-fpm

LABEL description="Automated plugins and themes installation for WordPress" \
     "com.koalaphils.vendor"="Koala Software Technology Innovations" \
     "com.koalaphils.image.author"="mdprotacio@outlook.com"

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    cron \
    rsync \
  ; \
  apt-mark manual '.*' > /dev/null; \
  savedAptMark="$(apt-mark showmanual)"; \
  apt-get install -y --no-install-recommends \
    libzip-dev \
  ; docker-php-ext-install -j "$(nproc)" \
    mysqli \
    pdo_mysql \
    zip \
  ; docker-php-ext-enable \
    imagick \
  ; \
  apt-mark auto '.*' > /dev/null; \
  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImport=false; \
  rm -rf /tmp/* ~/.pearrc /var/lib/apt/lists/* /var/cache/* \
  ;
COPY opt/php/*.ini /usr/local/etc/php/conf.d/
COPY --from=wordpress:cli /usr/local/bin/wp /usr/local/bin/wp
COPY --from=wordpress:fpm /usr/src /usr/src
COPY --from=wordpress:fpm /usr/local/bin/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY themes /usr/src/themes
COPY plugins /usr/src/plugins

RUN sed -i 's/exec\s*\"\$\@\"/source \/usr\/local\/bin\/post-install.sh/g' /usr/local/bin/docker-entrypoint.sh
COPY post-install.sh /usr/local/bin/post-install.sh
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]
